"""Simulation-mode schemas."""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from app.core.enums import RecommendedAction, RoomState, SimulationScenario
from app.schemas.analytics import RoomUpdateMessage

SIMULATION_NOTICE = "SIMULATED data generated by the backend - not measured by physical sensors."


class SimulationRequest(BaseModel):
    """Body of POST /simulation/generate."""

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {"room_id": 1, "scenario": "demo_story", "duration": 1800, "interval": 10},
                {"room_id": 1, "scenario": "demo_story", "duration": 1800, "interval": 10, "realtime": True, "speed": 30},
            ]
        }
    )

    room_id: int = Field(ge=1)
    scenario: SimulationScenario = SimulationScenario.DEMO_STORY
    duration: int = Field(default=1800, ge=10, le=86400, description="Simulated length in SECONDS")
    interval: int = Field(default=10, ge=1, le=600, description="Seconds between readings")
    realtime: bool = Field(
        default=False,
        description="False: generate everything instantly (history). True: stream in the background so "
        "a dashboard can watch the transitions live.",
    )
    speed: float = Field(
        default=1.0,
        gt=0,
        le=1000,
        description="Realtime only. 30 means 30 simulated seconds pass per real second. "
        "With speed > 1 the reading timestamps run ahead of the wall clock.",
    )
    seed: int | None = Field(default=None, description="Fix the random seed for reproducible data")
    clear_previous: bool = Field(
        default=True,
        description="Delete earlier SIMULATED data of this room first, so repeated demos do not add up "
        "in the energy estimates. Real (non-simulated) data is never deleted.",
    )


class SimulationTransition(BaseModel):
    """A moment where the room state or recommendation changed during a run."""

    timestamp: datetime
    room_state: RoomState
    recommended_action: RecommendedAction
    occupancy_confidence: float | None
    thermal_anomaly_score: float | None
    leak_candidate: bool


class SimulationResponse(BaseModel):
    """Response of POST /simulation/generate."""

    simulated: Literal[True] = True
    notice: str = SIMULATION_NOTICE
    run_id: str
    mode: Literal["batch", "realtime"]
    status: Literal["completed", "running", "stopped", "failed"]
    scenario: SimulationScenario
    room_id: int
    device_id: str
    readings_planned: int
    readings_generated: int
    start_time: datetime
    end_time: datetime
    transitions: list[SimulationTransition]
    final_state: RoomUpdateMessage | None = None
    error: str | None = None


class ScenarioInfo(BaseModel):
    """Description of one simulation scenario."""

    name: SimulationScenario
    description: str
    expected_outcome: str
    recommended_min_duration: int
